language: generic
sudo: false # use container based build

# set clone depth to false to make sure that conda build can write the
# correct GIT_BUILD_STR
git:
  depth: false

env:
    matrix:
        # python 3.8
        - PYTHON_VERSION=3.8 QT_VERSION=5 DEPLOY_CONDA=true
        - PYTHON_VERSION=3.8 USE_PIP=true
        # python 3.7
        - PYTHON_VERSION=3.7 QT_VERSION=5 DEPLOY_CONDA=true
        - PYTHON_VERSION=3.7 QT_VERSION=5 DEPLOY_CONDA=true BUILD_STR_END=
    global:
        - BUILD_STR_END=cf
        - secure: "erSMDYgwd78VvJwe6nhEJr/PKpyXG9GepNLzJ3vK/b+w8jMWp9LxZKOZtROhTs1SMYtKexDvHvBhuoBVZ2ysSCIuWPCPBI5wbfAvgaUvD8reHL3YJ33hSgtoVUenn6LFoFEqbNg73FfuKdwar7xVCggYtare6ud5Bali32BPyhVea07uY2DpN5FLKDSSRgoV8hDwqGAGlL/qiigkewS4yK18pbEkLus/FlyvsEWmaCUanWgW4JAprn1zrQ7al8WphooGYS9iAAMtdC1XiAN/P2tFsbxQQgVYPO0JalRePmyLvn3nwWU/JjLGVUmEZkK1FksOIrHQITQdl5DZHhcIGFPlIHf5li7jG4J6OAPqpQzq+cbbAHl0rPwyeBrKb6gBz+d52KcQKTkCoUYUvuq8T+sq7g+JWB1n4DHvmwA5krPeI6lMPLcv3BFiQ67aK2PKcM9qvEAfxO8odeTfPvzvyCP6hWTEfFRWozPIdZ6g1qw15szfBJ2jzIKtmljB68OLgLcavsOo1i6CszLNjeBoKb3AoVItTJTj4RqQrABPC2Jrd/1p6YU0hi6uK0xZk/X25p9TwsaefBpLi2sE2FpE2t0Aumw1KtjWn0z9pGXWkeceDfyUu+2KHJEnrtVuy/nr8gDXDuWZMRMQmHY7rc45bfZWbhfYjakC8Hc9c6eXhsY="

os:
    - linux
    - osx

services:
    - xvfb

matrix:
    allow_failures:
        - env: PYTHON_VERSION=3.8 USE_PIP=true

before_install:
    - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then export DEPLOY_CONDA=false; fi
    # Remove homebrew.
    - |
      if [[ $TRAVIS_OS_NAME == "osx" ]]; then
          echo ""
          echo "Removing homebrew from Travis CI to avoid conflicts."
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
          chmod +x ~/uninstall_homebrew
          ~/uninstall_homebrew -fq
          rm ~/uninstall_homebrew
      fi
    # define functions to unset and reset encrypted variables
    - function unset_secure {
          CONDA_TOKEN_SAVE=$CONDA_REPO_TOKEN;
          unset CONDA_REPO_TOKEN;
          }
    - function reset_secure {
          export CONDA_REPO_TOKEN=$CONDA_TOKEN_SAVE;
          }
    - unset_secure
    # increase open files limit
    - ulimit -a
    - ulimit -Sn 10000
    - ulimit -a
      # select the os name for the conda installer
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          OS_NAME=MacOSX;
      else
          OS_NAME=Linux;
      fi
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-${OS_NAME}-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -bp $HOME/miniconda3
    - source $HOME/miniconda3/bin/activate root
    - hash -r
    - reset_secure

before_script:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
          export "DISPLAY=:99.0";
          sh -e /etc/init.d/xvfb start;
          sleep 3;
      fi

install:
    # unset the global CONDA_REPO_TOKEN variable because it is not needed
    # during the tests. This decreases the vulnerability
    - unset_secure
    - |
        echo ""
        echo "Configuring conda."
        conda config --set always_yes yes --set changeps1 no
        if [[ ${BUILD_STR_END} == "cf" ]]; then
            conda config --add channels conda-forge
        else
            conda config --add channels chilipp/label/conda-forge
        fi
        conda config --add channels psyplot
        conda update -q conda
        conda install conda-build anaconda-client conda-verify
    - if [[ $TRAVIS_TAG == "" ]]; then
        export GIT_BRANCH=$TRAVIS_BRANCH;
        conda config --add channels psyplot/label/master;
        conda config --add channels psyplot/label/${TRAVIS_BRANCH};
      fi
    - python ci/setup_append.py ci/conda-recipe pyqt=${QT_VERSION}
    - if [[ $USE_PIP == true ]]; then
        python -m pip install . -r ci/requirements.txt;
      fi
    - conda info -a
    - conda list
    - reset_secure
script:
    - unset_secure
    # install conda
    - if [[ $USE_PIP == true ]]; then
          pytest -v --cov=psy_view && codecov;
      else
          conda build ci/conda-recipe --python $PYTHON_VERSION;
      fi
    # export the pw to make it available for the deploy
    - reset_secure
    # deploy here (don't use travis deploy because it requires homebrew)
    - if [[ $DEPLOY_CONDA == "true" && $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_REPO_SLUG == "psyplot/psy-view" ]]; then
          ci/deploy_anaconda.py;
      fi
